services:
  backend:
    build:
      context: .
      target: backend
    container_name: ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
    env_file:
      - ./back-end/.env

  frontend:
    build:
      context: .
      target: frontend
    container_name: ai-frontend
    ports:
      - "3000:3000"

